### ISSUE TITLE
Embedding tfrecords doesn't work

### ISSUE THREAD

**Issue by goaaron** [songlab-cal/tape-neurips2019#12]
Tensorflow complains about the datafile being passed as a PosixPath. this is fixed if you cast the path to a string in run_embed.py

**Comment by proto-tardigrade** [comment]
@goaaron I was having issues with run_embed.py as well, but they seemed to be syntax issues, which I believe was because I was using python 3.5. However when switching to 3.7 I'm not able to install tensorflow-gpu, which appears to be required for TAPE installation. What python version are you using, and did you come across any similar issues?

**Comment by goaaron** [comment]
Yep, tensorflow-gpu is kind of a mess and not working with the newer version of python. I think you can still use all the models  but the LSTM with the latest python if you remove it from the setup.py.  

I think something is buggy about the Lstm too since I will often get a cuda_dnn.c error tensorflow/stream_executor/cuda/cuda_dnn.cc:1218] Check failed: seq_length > 0 (0 vs. 0)

**Comment by rmrao** [comment]
Thanks for pointing this out. Fixed the original PosixPath issue by casting `datapath` to string in this [commit](b31ebf35557e618e57cd8545c1e46b7606be60db).

**Comment by rmrao** [comment]
I am also working on a pytorch version of this code at the moment, which generally seems to be much more stable and easier to use. It'll probably be released in a few months.
