### ISSUE TITLE
Adding models to the benchmark

### ISSUE THREAD

**Issue by bl-2633** [songlab-cal/tape-neurips2019#4]
Hi, I am wondering if there is a way to add models that are not currently included in the benchmark?

**Comment by rmrao** [comment]
Yes. I should add a section in the README on this, but it's fairly straightforward.

You can basically follow the example of any of the models in `tape/models`. Subclass the `AbstractTapeModel`, make sure your model takes a dictionary (in particular `['primary']` is the key for the protein sequence and `['protein_length']` is the key for the length). Then import your model in `ModelBuilder` and add it to the list. Alternatively we added a `register_model` function to the `ModelBuilder` class which you can use to register your model instead of editing the `ModelBuilder` file. Just make sure that the register call is run before you try to build the model.

The other major thing you have to do is define the batch sizes for the model in `get_optimal_batch_sizes`. This is because our code batches different examples by sequence length. To start, you should just be able to copy the method from an existing model. If you find that you're running out of memory, you can progressively decrease the batch sizes until you have enough memory.

**Comment by rmrao** [comment]
I will see if I can create a notebook or an example on how to do this at some point.

**Comment by rmrao** [comment]
Alright, I added a [section](https://github.com/songlab-cal/tape#extending-tape) to the README and examples in [this directory](https://github.com/songlab-cal/tape/tree/master/examples).

I believe this should be straightforward enough to extend - if not then please either reopen this issue or create a new one.

**Comment by mniepert** [comment]
Apologies if I'm missing something here, but I tried to follow the instructions and I always get the error message 

> ValueError: Input 0 of layer conv1d is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [None, 32]

even though my model doesn't have a conv1d layer. It seems like the error message is coming from a call to the model 'AminoAcidClassPredictor.py'. This only happens when I change the conv1d layer in the example files to something else. Running the original example file works. What am I missing? 

To reproduce, simply replace, in simple_model.py, the conv1d layer by an LSTM layer and adjust the file accordingly. Then run 
> python examples/simple_model.py with model=my_simple_model tasks=secondary_structure

**Comment by mniepert** [comment]
Please ignore the previous comment.  I forgot to set return_sequences to True (so as to return a sequence of embeddings) and the error message was caused by this.
